### ISSUE TITLE
You have not accepted the license agreements of the following SDK components: [Google Repository].

### ISSUE THREAD

**Issue by muzammilahmed** [ionic-team/ionic-cli#1726]
I'm using cordova push plugin plugin for push notifications I've installed google repository and google play services packages from android SDK manager., but when ever I execute ionic build android to create build its gives me following error.

FAILURE: Build failed with an exception.

BUILD FAILED

Total time: 13.856 secs

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
[Google Repository].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
[Google Repository].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by Fenmingyu** [comment]
I also encountered this problem today.
Please help me IF you solved this problem.
Thanks

**Comment by IgorGanapolsky** [comment]
Did you find a solution to this problem?  I am facing a similar issue.

**Comment by smitthakkar96** [comment]
ionic team is really slow in terms of replying to issues. I started facing the issue when I installed phonegap-push-plugin

**Comment by smitthakkar96** [comment]
I found the fix it's because there are two missing packages called google repository and android repository. You can go to android sdk manager by android sdk command and navigate to extras folder there you can select both packages and install them. The issue will be resolved.

**Comment by IgorGanapolsky** [comment]
@smitthakkar96 Those licenses should have already been downloaded to android-sdk-home/licenses directory.

**Comment by smitthakkar96** [comment]
@IgorGanapolsky No those aren't, they are really large packages. Can you please put effort to check whether Google Repository Package is installed or not.

**Comment by esase** [comment]
I solved this problem just installed these components in "Android 7.0 (API 24)":
SDK platform
Google Apis
Sources for android SDK

**Comment by ksummersill** [comment]
Thank you esase for posting this. I even installed the 7.1.1  (API  25) but no luck. I installed just the SDK platform, Google APIs, and Sources for Android SDK; the build was successful.

**Comment by killerbytes** [comment]
Take note which API level and install that version

**Comment by Jojr** [comment]
@ksummersill You need to install the "Android 7.0 (API 24)" and not "Android 7.1.1 (API 25).

**Comment by BattleToads** [comment]
Configure > SDK Manager > Launch Standalone SDK Manager

**Comment by gbrits** [comment]
You will run into an issue like this whenever your Android Studio's packages are outdated, as building will occur in the latest stable releases. To fix, do the following:

**Android Studio > Preferences > Appearance & Behavior > System Settings > Android SDK**
Tick the latest Android versions, click Apply.
It's at this point where Android will ask you to agree to its license(s) and the updated version(s) will be installed. Now you can Ionic / Cordova / PhoneGap build / run.

**Comment by RafatAssaf** [comment]
I just checked for updates in Android studio settings, installed them, and the problems was solved.

**Comment by raghulrajnkl** [comment]
Update the your android gradle, its working fine

**Comment by SKempin** [comment]
@gbrits 
I'm still getting the following error after installing the latest SDK's. Any advice? Thanks!
```
Checking the license for package Google Repository in /usr/local/Caskroom/android-sdk/3859397,26.0.1/licenses
Warning: License for package Google Repository not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
  [Google Repository].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
<img width="713" alt="screen shot 2017-11-07 at 23 20 17" src="https://user-images.githubusercontent.com/10877466/32523259-7a62b418-c412-11e7-8412-8f7c3bc1ccee.png">
<img width="711" alt="screen shot 2017-11-07 at 23 20 03" src="https://user-images.githubusercontent.com/10877466/32523260-7a80ee56-c412-11e7-92ea-35c3d5eb896c.png">

**Comment by amed** [comment]
@SKempin 
Just run $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-26" and accept it.

**Comment by DeepzSandra** [comment]
I'm still getting the following error after installing the latest SDK's. Any advice? Thanks!

Checking the license for package Google Repository in /usr/local/Caskroom/android-sdk/3859397,26.0.1/licenses
Warning: License for package Google Repository not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
  [Google Repository].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by dwieeb** [comment]
The solution for Android Studio is here -> https://github.com/ionic-team/ionic-cli/issues/1726#issuecomment-279164447

The solution for Android SDK (stand-alone) is here -> https://github.com/ionic-team/ionic-cli/issues/1726#issuecomment-343827530

I'll expand on the latter a bit.

First, make sure you have the latest Android SDK installed. 
Second, make sure `ANDROID_HOME` is set. (`echo $ANDROID_HOME`)

:memo: _If the `ANDROID_HOME` environment variable is **not** set, take a look at this guide: https://spring.io/guides/gs/android/#android-dev-env_

These commands may need slight tweaking for Windows:

```bash
cd $ANDROID_HOME 
./tools/bin/sdkmanager --licenses
```

The sdk manager utility will walk you through licenses which need accepting.

**Comment by chingwen823** [comment]
check Google APIs 23.0.1 up in Android studio
accept all license with sdkmanager --license

and the bug gone.

**Comment by renjithvk** [comment]
You can simply solve that. Please open `platforms/android` in Android studio. Then it shows the same error in Build log as an error. There you can find the link to the missing agreement. You can simply click it to download and accept.

**Comment by andreszs** [comment]
If you are using the Android SDK Manager GUI and license is still rejected, try this which worked for me:
- Remove the platforms\android-26 folder.
- Run `sdkmanager "platforms;android-26"` in the android-sdk\bin folder.
- Press y to accept the license and wait until it's installed.

**Comment by joese6** [comment]
Open the "sdkmanager.bat --update" via command line then select "Y" , enter and wait until finish.
as and example, I use the command line to enter the directory : "E:\android-sdk_r24.4.1-windows\android-sdk-windows\tools\bin"
then i type : sdkmanager.bat --update

I hope this helps.

**Comment by s2zaman** [comment]
My $ANDROID_HOME was set to sdk-root-directory/tools/bin

I Updated the $ANDROID_HOME to its correct path sdk-root-directory
and added to PATH as $ANDROID_HOME/tools/bin
:)

**Comment by joese6** [comment]
![screenshot_68](https://user-images.githubusercontent.com/41458819/43124837-79a6c68e-8f52-11e8-8ee6-1eb20db60496.jpg)
I added this : E:\android-sdk_r24.4.1-windows\android-sdk-windows\tools;E:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools

then, in command line i type : sdkmanager.bat --update .

**Comment by hvsombrilla** [comment]
If the problem persists you can try reinstalling the platform

```
ionic cordova platform rm android
ionic cordova platform add android
```

**Comment by lukdeboss** [comment]
actually you can just go to cmd
find where you have SDK installed and cd to tools/bin
execute in exmaple:
./sdkmanager "platforms;android-26"
and accept license with y

**Comment by SnehalAgrawal** [comment]
You can face this problem if you have installed the SDK but have not accepted the license agreement.
To solve this problem you just need to accept the terms and conditions of the SDK component. To accept the terms and conditions you can use a command line tool sdkmanager.
You can solve the issue in 2 steps:
1. Go to SDK -> tool -> bin using the following command
`cd C:\Users\Admin\AppData\Local\Android\Sdk\tools\bin`
2. Run the following command to ask for licenses acceptance
`sdkmanager --licenses`

![you_have_not_accepted_the_license_agreements_of_the_following_sdk_components2](https://user-images.githubusercontent.com/29939757/52884060-eea09b80-3192-11e9-923f-77bf408dc405.png)

If anybody still facing the issue then please follow the link for the solution 
https://aboutreact.com/you-have-not-accepted-the-license-agreements-of-the-following-sdk-components/

**Comment by ayoubkhan558** [comment]
You just need to install your android SDK/build tools. 

![sdfd](https://user-images.githubusercontent.com/20210961/60965100-6fbd2280-a32e-11e9-833f-93b844e3e6f5.jpg)

**Comment by dwieeb** [comment]
For those coming to this issue now... 

### The solution is here 👉  https://github.com/ionic-team/ionic-cli/issues/1726#issuecomment-279164447

If you **don't** use Android Studio, here's what you have to do: https://github.com/ionic-team/ionic-cli/issues/1726#issuecomment-352219584
