### ISSUE TITLE
Make project file (ionic.config.json) configurable via enviornment or CLI flags

### ISSUE THREAD

**Issue by timbru31** [ionic-team/ionic-cli#2527]
**Description:**
I'd like to make the `ionic.config.json` file name and location configurable.
It's currently hardcoded in https://github.com/ionic-team/ionic-cli/blob/965af07a517b5ec5ab8ced6deea2c7b62b26d709/packages/cli-utils/src/index.ts#L147. The env var will be set to the found config file, but there is no option to override the project file configuration folder and/or file.

Background: We'd like to have a separate app_id since we don't want to mix the Auth feature of Ionic with different users groups. (i.e. we don't want to use the same database for production and development)

**Steps to Reproduce:**
n/a

**Output:**
n/a

**My `ionic info`:**
```
[INFO] --no-confirm: Detected ./gulpfile.js in project directory, but to integrate gulp with the CLI, you'll need to
       install @ionic/cli-plugin-gulp. Install now? No
[INFO] --no-confirm: Looks like this is an Ionic Angular project, would you like to install
       @ionic/cli-plugin-ionic-angular and continue? No
[WARN] You have no CLI project plugins installed. CLI functionality may be limited.

global packages:

    @ionic/cli-utils : 1.5.0
    Ionic CLI        : 3.5.0

System:

    Node       : v6.11.1
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9M137d
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10
```

**Other Information:**
n/a

**Comment by dwieeb** [comment]
@timbru31 Great idea. Yeah, it's hardcoded right now, but it's really only hardcoded in one or two places.

**Comment by dwieeb** [comment]
@timbru31 I think this might be better solved with a multi-app project configuration. This is still undocumented.

**Comment by dwieeb** [comment]
@timbru31 Multi-app documentation for CLI 4.3.0+: https://beta.ionicframework.com/docs/cli/configuration#multi-app-projects

So here's a potential solution using a multi-app configuration for different app_ids in Ionic Pro:

`ionic.config.json`
```
{
  "defaultProject": "my-app",
  "projects": {
    "my-app": {
      "name": "my-app",
      "integrations": {},
      "type": "angular",
      "root": ".",
      "pro_id": "123abc"
    },
    "my-app-prod": {
      "name": "my-app-prod",
      "integrations": {},
      "type": "angular",
      "root": ".",
      "pro_id": "abc123"
    }
  }
}
```

Both apps have a different `pro_id` _but_ they share the same `root`. You would be able to switch to the prod version via `ionic <command> --project=my-app-prod`. 

Let me know what you think. I think Ionic Pro has plans to improve environment support (development vs production) internally as well.

**Comment by timbru31** [comment]
Thanks for the example and the added documentation. The main issue remains though: Ionic Pro is unable to understand this config and does not build the app.  
The original issue was written when we had Ionic v1 with Auth etc, nowadays we don't need two project configs anymore.

I believe multi app/config projects are the way to go 👍

**Comment by dwieeb** [comment]
@timbru31 Great, thanks! The Pro team is aware of multi-app config. I presume the announcement will be in the [Product Updates](https://ionic.zendesk.com/hc/en-us/sections/360000954533-Product-Updates) or the monthly newsletter.
