### ISSUE TITLE
Ionic Error: An error occurred while running subprocess cordova

### ISSUE THREAD

**Issue by mwq27** [ionic-team/ionic-cli#3690]
**Description:**

Running `ionic cordova build...` command errors with output like below
```shell
...
:cdvBuildDebug

BUILD SUCCESSFUL

Total time: 8.893 secs
Command finished with error code 0: /Users/marqueswoodson/Projects/platforms/android/gradlew cdvBuildDebug,-b,/Users/marqueswoodson/Projects/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Dorg.gradle.jvmargs=-Xmx2048m,-Pandroid.useDeprecatedNdk=true,-PcdvCompileSdkVersion=android-28
Built the following apk(s):
	/Users/marqueswoodson/Projects/platforms/android/build/outputs/apk/android-debug.apk
No scripts found for hook "after_compile".
No scripts found for hook "after_build".
[ERROR] An error occurred while running subprocess cordova.

        cordova build android --verbose -- --gradleArg=-PcdvCompileSdkVersion=android-28 exited with exit
        code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:cli-framework:utils:process onBeforeExit handler: process.exit received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 2 queued functions +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 1) +72ms
``` 
The actual build does work, as you can see above.  There's no errors in the output.

**Steps to Reproduce:**

Try building an android project with ionic 4.x.

If I run the above without the ionic keyword:
```shell
cordova build android --verbose -- --gradleArg=-PcdvCompileSdkVersion=android-28
```
it works fine.

**Output:**

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI) : 4.1.2 (/Users/marqueswoodson/.nvm/versions/node/v8.9.4/lib/node_modules/ionic)
   Ionic Framework   : unknown
   @ionic/v1-toolkit : 1.0.10

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : no whitelisted plugins (25 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/marqueswoodson/android-sdk)
   NodeJS            : v8.9.4 (/Users/marqueswoodson/.nvm/versions/node/v8.9.4/bin/node)
   npm               : 2.15.12
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255
```

**Other Information:**

**Comment by dwieeb** [comment]
@mwq27 After running `cordova build android --verbose -- --gradleArg=-PcdvCompileSdkVersion=android-28`, if you run `echo $?`, what does it print? This is the exit code of the previous command in bash. If it prints `1`, the command has exited with an error.

Perhaps it has something to do with this output re: hooks? 

```
No scripts found for hook "after_compile".
No scripts found for hook "after_build".
```

What does your `config.xml` contain for these hooks?

**Comment by mwq27** [comment]
Running `echo $?` prints out 1.  I didn't think the hooks for after_compile and after_build were a required thing, since we've never had anything before.  We are still using the deprecated method for defining hooks (the `/hooks` directory).  Would you recommend defining my hooks in the `config.xml` instead?

**Comment by mwq27** [comment]
Ok I believe I fixed the issue in my project.  The issue was a plugin wasn't installing during the builds, and since that part was failing, it was giving the exit 1.  All I did was manually install the errant plugin, and now the ionic commands run like normal.

**Comment by shahrulhaniff** [comment]
in case of others who still not fixed yet, I remove the platform folder, then run the cmd again. Its work fine with me

**Comment by dwieeb** [comment]
Locking this issue, see https://github.com/ionic-team/ionic-cli/issues/3673#issuecomment-429364015
