### ISSUE TITLE
HTTP Error 400: POST https://res.ionic.io/api/v1/upload

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-cli#3910]
**Description:**
I am not able to generate splash using below cmd
ionic cordova resources  -f --splash --verbose --cordova-res
ionic cordova resources -f --splash --verbose 
but still it is same.

**Steps to Reproduce:**
create one splash of 2732* 2732 and place it in resources.

**Output:**
D:\vee-crm>ionic cordova resources  -f --splash --verbose
  ionic:lib Terminal info: { tty: true, ci: false, windows: true } +0ms
  ionic:lib CLI global options: { _: [ 'cordova', 'resources' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, f: true, splash: true, project: null, '--': [] } +5ms
  ionic:lib:project Project type from config: Ionic 2/3 (ionic-angular) +0ms
  ionic:lib:project Project details: { configPath: 'D:\\vee-crm\\ionic.config.json', errors: [], context: 'app', type: 'ionic-angular' } +1ms
  ionic Context: { binPath: 'C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath: 'C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules\\ionic', execPath: 'D:\\vee-crm', version: '4.4.0' } +0ms
  ionic:lib:integrations:cordova:config Using config.xml: D:\vee-crm\config.xml +0ms
  ionic:lib:integrations:cordova:config Using config.xml: D:\vee-crm\config.xml +40ms
  ionic:commands:cordova:resources RESOURCES=3 +0ms
  ionic:commands:cordova:resources installedPlatforms=android +9ms
  ionic:commands:cordova:resources buildPlatforms=android +1ms
  ionic:commands:cordova:resources imgResources=12 +4ms
  ionic:commands:cordova:resources createImgDestinationDirectories completed: 1 +1ms
  ionic:commands:cordova:resources getSourceImages completed: (.\resources\splash.png) +11ms
  ionic:commands:cordova:resources imgResources=12 +1ms
√ Collecting resource configuration and source images - done!
√ Filtering out image resources that do not need regeneration - done!
  superagent creating `fs.ReadStream` instance for file: D:\vee-crm\resources\splash.png +0ms
  superagent POST https://res.ionic.io/api/v1/upload +25ms
  superagent setting FormData header: "content-type: multipart/form-data; boundary=--------------------------795353847425759390267165" +2ms
\ Uploading source images to prepare for transformations
- Uploading source images to prepare for transformations
  superagent POST https://res.ionic.io/api/v1/upload -> 400 +2s
HTTP Error 400: POST https://res.ionic.io/api/v1/upload

- Uploading source images to prepare for transformations

**My `ionic info`:**

```
D:\vee-crm>ionic info

Ionic:

   ionic (Ionic CLI)  : 4.4.0 (C:\Users\HP\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 17 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\HP\AppData\Local\Android\Sdk)
   NodeJS            : v8.14.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

```

**Other Information:**

**Comment by dwieeb** [comment]
@indraraj26 What is the output of `ionic cordova resources -f --splash --verbose --cordova-res`?

**Comment by dwieeb** [comment]
@indraraj26 Update your Ionic CLI to the latest version.

**Comment by indraraj26** [comment]
Thank you @dwieeb  btw i had to re-save the splash using paint 
Now it is resolved.

**Comment by fpassa** [comment]
Still having the same issue with CLI 4.12.0
`Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.6
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 9.0.0
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 7 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/flavio/Library/android-sdk-macosx)
   ios-deploy        : 2.0.0
   ios-sim           : 7.0.0
   NodeJS            : v10.15.0 (/usr/local/bin/node)
   npm               : 6.8.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
`

**Comment by Dr-Bonsai** [comment]
Having Same problem 

Also using a macOS

**Comment by Dr-Bonsai** [comment]
> Having Same problem
> 
> Also using a macOS

Seems it was just a problem with the image itself not cordova

**Comment by Piashsarker** [comment]
Is there any update , I am also facing this weird error in _**IONIC V 4.1.2 , Cordova V8.1.2**_ 


![image](https://user-images.githubusercontent.com/8473499/59755625-14a58c00-92aa-11e9-8dfd-bfdfde969bb3.png)

**Comment by anh1979** [comment]
Having the same issue right now. Our images haven't changed. Frustrating!

**Comment by MaBbKhawaja** [comment]
There is a problem with one of your images so change the images and then try again
