### ISSUE TITLE
ionic cordova build iOS hangs only when iphone attached to Mac

### ISSUE THREAD

**Issue by rolinger** [ionic-team/ionic-cli#4156]
**Description:**
Using cli 5.2.6, running Ionic v1 app - running `ionic cordova build iOS` hangs the app after this file is compiled ONLY if an iPhone is attached to the Mac.  Disconnect the iPhone and it compiles just fine.  Running `cordova build iOS` builds just fine even with an iPhone connected to the Mac.

`platforms/ios/build/sharedpch/SharedPrecompiledHeaders/6268428044778614059/MyApp-Prefix.pch.dia`

<edit correction>

I suspect it "might" be related to `Cordova-plugin-firebasex` - this is happening with firebasex plugin versions 6x and higher.  I brought this to the attention of the plugin owner/developer (Dave Allen) and he believes its a ionic cordova build wrapper issue as the issue doesn't happen when just doing `cordova build iOS`.

My Environment:

```
Ionic:

   Ionic CLI         : 5.2.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.0.0
   @ionic/v1-toolkit : 1.0.22

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, (and 32 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.11.2
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61
```

Plugins:
```
cl.rmd.cordova.dialoggps 0.0.2 "DialogGPS"
com.lampa.startapp 6.1.6 "startApp"
com.ludei.webview.plus 2.3.0 "Webview+"
com.peerio.cordova.plugin.carrier 1.0.1 "Carrier"
com.phonegap.plugins.nativesettingsopener 1.0.1 "Native settings"
cordova-admobsdk 7.37.0 "Google Mobile Ads SDK for Cordova"
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-instagram-plugin 0.5.8 "Instagram"
cordova-launch-review 3.1.1 "Launch Review"
cordova-plugin-admobpro 2.37.2 "AdMob Plugin Pro"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-appinfo 2.1.2 "AppInfo Plugin"
cordova-plugin-customurlscheme 4.4.0 "Custom URL scheme"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-device-motion 2.0.1 "Device Motion"
cordova-plugin-device-orientation 2.0.1 "Device Orientation"
cordova-plugin-deviceinformation 2.0.2 "DeviceInformation"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-email 1.2.7 "EmailComposer"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-facebook4 6.0.0 "Facebook Connect"
cordova-plugin-fastrde-checkgps 0.9.9 "checkGPS"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 6.1.0 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-queries-schemes 0.1.1 "App Queries Strings"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-screensize 1.3.1 "screensize"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sms-plugin 1.0.0 "Cordova SMS Plugin"
cordova-universal-clipboard 0.1.0 "Clipboard"
cordova.plugins.diagnostic 5.0.0 "Diagnostic"
twitter-connect-plugin 0.6.0 "Twitter Connect"
```

**Comment by theopavan** [comment]
This errors occurs with 'ionic cordova build ios --device' in Ionic 4 too ... 
it's OK with the command 'ionic cordova prepare ios --prod && cordova build ios --device' 
see https://github.com/dpa99c/cordova-plugin-firebasex/issues/5#issuecomment-530800679

**Comment by FMEDev** [comment]
Any updates on this? I'm having the same issue also using the firebasex plugin

**Comment by nstokoe** [comment]
Any updates on this? I'm having the same issue also using the firebasex plugin

**Comment by rolinger** [comment]
I upgraded firebasex to v6.1.0 and issue is still happening.  The work around still works, but ultimately this needs to be resolved.  If I remove the firebasex plugin `ionic cordova build ios` completes properly, but with the plugin installed in the project it hangs at that same spot every time - it also hangs running `ionic cordova run ios` too.  Because it builds fine with just `cordova build ios` I suspect the issue must lie with Ionic.

**Comment by dwieeb** [comment]
Looks like something in the build process is hanging unless it gets full access to the parent process's stdio streams. I pushed a commit in the Ionic CLI that should fix this.

**Comment by dwieeb** [comment]
CLI 5.3.0 is out and should fix this!

**Comment by nstokoe** [comment]
I just upgraded to CLI 5.3.0 and it still hangs...

**Comment by brownoxford** [comment]
I am also still encountering this problem, and believe that I've narrowed it down to the handoff between `ionic cordova compile` and `cordova compile`.

This works:
```bash
cordova compile ios --debug --device \
  --packageType=development \
  --developmentTeam=MYTEAMID
```

This does not, and hangs on ProcessPCH:
```bash

[debugging.json.zip](https://github.com/ionic-team/ionic-cli/files/3637012/debugging.json.zip)
ionic cordova prepare ios --no-interactive --debug --device -- \
  --packageType=development \
  --developmentTeam=MYTEAMID
```

```
$ ionic info

Ionic:

   Ionic CLI          : 5.3.0 (/Users/cabernet/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.8
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic 5.4.4, cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 12 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/Users/cabernet/.nvm/versions/node/v10.16.3/bin/node)
   npm        : 6.11.3
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8
```

```
cordova plugin list

cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-customurlscheme 4.4.0 "Custom URL scheme"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-firebasex 6.1.0 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-ionic 5.4.4 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-safariviewcontroller 1.6.0 "SafariViewController"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 3.3.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
sentry-cordova 0.16.0 "Sentry"
```

I've also dumped the process and subprocess objects from `Shell.run()` in ionic/lib for the failed job, and have attached the output
[as a zip file](https://github.com/ionic-team/ionic-cli/files/3637024/debugging.json.zip)
.

```typescript
debug(`proc: ${JSON.stringify(proc)}`);
debug(`sub: ${JSON.stringify(promise.p)}`);
```

**Comment by dwieeb** [comment]
Thanks @brownoxford. I believe I just forgot to switch on stdio inheritance for prepare and compile.

**Comment by dwieeb** [comment]
Ionic CLI 5.4.1 has this fix. Thanks again

**Comment by brownoxford** [comment]
Fix confirmed, both in my test case documented on https://github.com/dpa99c/cordova-plugin-firebasex/issues/5 and in my main project fastlane build.

Thanks!
