### ISSUE TITLE
ionic cordova run iOS --device freezes after build with no error

### ISSUE THREAD

**Issue by fatinyazi** [ionic-team/ionic-cli#4165]
**Description:**
When I tried to run my app on iOS with my device connected to my Mac, the build will freeze at the native-run command and nothing happens afterward. No error is displayed and the app is not deployed to the device. It only happens with the `--device` flag. It works fine when deployed via Xcode or to simulator without the `--device` flag.

**Steps to Reproduce:**
run `ionic cordova run iOS --prod --release --device`

**Output:**
Running `ionic cordova run iOS --prod --release --device` freezes at the following with no error and nothing happens after:

`native-run ios --app "platforms/ios/build/device/MyApp.ipa" --device`

Running with `--verbose` will have it stuck at:

`[native-run] 2019-09-24T14:29:08.271Z protocol:usbmux Response: {"PairRecordData":{"type":"Buffer","data":[60,63,120,109,108,32,118,101,114,115,105,111,110,61,34,49,46,48,34,32,101,110,99,111,100,105,110,103,61,34,85,84,70,45,56,34,63,62,10,60,33,68,79,67,84,89,80,69,32,112,108,105,115,116,32,80,85,66,76,73,67,32,34,45,47,47,65,112,112,108,101,47,47,68,84,68,32,80,76,73,83,84,32,49,46,48,47,47,69,78,34,32,34,104,116,116,112,58,47,47,119,119,119,46,97,112,112,108,101,46,99,111,109,47,68,84,68,115,47,80,114,111,112,101,114,116,121,76,105,115,116,45,49,46,48,46,100,116,100,34,62,10,60,112,108,105,115,116,32,118,101,114,115,105,111,110,61,34,49,46,48,34,62,10,60,100,105,99,116,62,10,9,60,107,101,121,62,68,101,118,105,99,101,67,101,114,116,105,102,105,99,97,116,101,60,47,107,101,121,62,10,9,60,100,97,116,97,62,10,9,76,83,48,116,76,83,49,67,82,85,100,74,84,105,66,68,82,86,74,85,83,85,90,74,81,48,70,85,82,83,48,116,76,83,48,116,67,107,49,74,83,85,78,49,97,107,78,68,81,87,70,76,90,48,70,51,83,85,74,66,90,48,108,67,81,85,82,66,10,9,84,107,74,110,97,51,70,111,97,50,108,72,79,88,99,119,81,107,70,82,86,85,90,66,82,69,70,66,84,85,73,48,87,69,82,85,82,84,86,78,82,71,116,51,84,87,112,70,77,48,49,69,87,84,65,75,84,109,120,118,87,69,82,85,83,84,86,78,10,9,82,71,100,54,84,85,82,70,77,48,49,69,87,84,66,79,98,71,57,51,81,85,82,68,81,48,70,84,83,88,100,69,85,86,108,75,83,50,57,97,83,87,104,50,89,48,53,66,85,85,86,67,81,108,70,66,82,71,100,110,82,86,66,66,82,69,78,68,10,9,81,86,70,118,81,119,112,110,90,48,86,67,81,85,116,115,90,48,107,53,100,49,104,49,77,108,81,114,87,70,85,49,100,87,100,113,99,108,70,114,97,50,52,114,99,51,78,113,84,68,100,83,78,87,115,121,83,84,100,75,86,51,103,121,76,50,53,104,10,9,99,72,104,115,81,85,100,78,87,109,81,50,97,110,108,107,84,88,100,79,83,108,90,81,67,108,66,111,99,88,74,90,98,107,74,117,87,87,90,53,78,87,57,50,89,84,100,112,84,106,86,79,90,109,86,67,97,84,86,110,90,69,108,79,85,69,104,122,10,9,100,48,69,49,84,87,56,119,77,85,120,88,90,69,53,118,75,50,112,108,84,48,49,77,100,85,112,112,82,71,74,85,100,106,77,118,89,107,49,109,78,88,81,75,86,109,116,81,77,107,120,116,86,107,53,105,77,88,108,77,85,87,100,89,79,87,104,82,10,9,79,68,100,74,84,108,90,113,81,50,90,69,76,51,100,81,87,84,86,73,98,105,116,112,83,85,120,105,89,122,74,106,78,107,108,71,101,109,77,119,87,108,112,104,89,48,53,51,82,70,69,114,85,107,74,86,97,121,57,97,87,81,112,122,100,110,112,118,10,9,83,84,99,118,85,107,112,120,84,109,53,85,87,71,53,84,82,122,82,104,75,49,108,48,98,70,85,49,89,107,103,122,97,69,89,114,84,106,66,78,90,86,65,114,83,84,90,108,87,106,65,48,85,109,112,87,83,50,120,77,79,69,108,74,84,83,116,67,10,9,99,86,86,118,89,110,66,97,90,106,78,88,67,107,74,76,79,85,120,75,101,67,116,86,89,109,120,72,84,86,66,119,86,122,108,49,78,86,77,122,84,84,78,116,100,109,52,120,85,85,74,79,78,69,74,84,77,70,104,79,98,88,86,74,78,87,100,67,10,9,99,86,78,77,101,85,112,66,101,87,81,122,79,71,86,48,87,72,82,108,99,107,104,52,79,85,78,49,78,70,111,75,77,71,57,48,78,71,100,74,81,108,90,82,85,85,89,48,89,107,56,53,83,84,70,120,97,121,115,114,87,70,100,71,77,72,107,119,10,9,81,48,70,51,82,85,70,66,89,85,48,118,84,85,81,119,100,48,82,66,87,85,82,87,85,106,66,85,81,86,70,73,76,48,74,66,83,88,100,66,82,69,70,107,81,109,100,79,86,103,112,73,85,84,82,70,82,109,100,82,86,86,78,109,90,49,100,120,10,9,77,107,53,120,99,108,90,69,79,69,77,50,86,84,86,84,82,49,90,111,84,70,104,84,97,88,66,72,86,88,100,69,90,49,108,69,86,108,73,119,85,69,70,82,83,67,57,67,81,86,70,69,81,87,100,88,90,48,49,66,77,69,100,68,85,51,70,72,10,9,67,108,78,74,89,106,78,69,85,85,86,67,81,108,70,86,81,85,69,48,83,85,74,66,85,85,78,79,78,69,78,82,79,71,116,113,101,106,78,114,84,110,82,52,98,71,74,72,81,87,53,49,98,85,52,120,89,106,82,108,100,48,82,120,98,87,78,71,10,9,82,70,104,120,89,107,104,120,82,72,108,122,83,109,73,119,97,86,81,75,83,106,78,121,89,51,108,80,87,68,107,121,86,108,86,76,85,70,70,122,87,107,52,119,84,110,100,75,78,71,53,70,98,51,90,106,76,49,111,119,82,85,90,70,85,68,77,49,10,9,89,87,74,67,101,86,74,78,81,87,86,51,99,86,66,119,83,50,86,119,86,109,111,118,83,106,69,119,79,84,74,70,98,106,86,83,98,119,112,53,98,121,116,97,99,108,108,97,84,87,90,49,97,110,107,121,85,107,108,97,89,49,78,86,85,49,89,118,10,9,87,88,69,50,87,87,100,50,77,107,120,112,100,85,111,50,101,87,82,108,90,48,111,50,87,85,78,68,90,85,107,48,86,50,57,70,98,107,74,67,85,109,108,76,97,72,65,53,82,109,120,73,86,88,100,76,67,110,104,111,78,49,104,86,89,84,70,122,10,9,86,87,100,79,83,49,74,70,85,107,104,77,98,87,49,112,101,106,70,84,78,49,90,80,97,122,70,83,100,85,89,121,75,121,116,84,77,51,111,121,77,51,78,97,78,85,82,97,90,122,86,118,78,88,89,120,83,122,104,69,87,106,78,52,85,122,86,109,10,9,84,108,66,73,89,107,103,75,82,84,78,105,89,110,74,84,87,87,90,113,99,68,100,53,77,87,49,50,100,50,120,72,90,87,53,112,100,109,99,119,89,110,69,118,81,86,70,121,89,50,119,118,89,50,70,110,89,87,120,80,81,85,77,114,87,108,86,77,10,9,82,51,112,117,77,69,112,78,83,68,82,84,84,72,74,70,99,51,100,53,87,87,86,85,86,81,112,72,98,108,70,76,82,86,90,79,98,72,103,51,101,109,57,87,89,107,103,50,90,85,70,72,83,50,108,76,82,108,66,90,97,72,66,121,101,87,70,104,10,9,81,86,104,52,77,68,74,66,85,86,107,119,67,105,48,116,76,83,48,116,82,85,53,69,73,69,78,70,85,108,82,74,82,107,108,68,81,86,82,70,76,83,48,116,76,83,48,75,10,9,60,47,100,97,116,97,62,10,9,60,107,101,121,62,69,115,99,114,111,119,66,97,103,60,47,107,101,121,62,10,9,60,100,97,116,97,62,10,9,117,103,83,122,51,68,51,103,114,69,78,79,85,78,71,119,48,82,53,122,79,114,97,110,90,48,102,121,68,116,103,118,56,73,79,99,53,72,98,114,43,80,111,61,10,9,60,47,100,97,116,97,62,10,9,60,107,101,121,62,72,111,115,116,67,101,114,116,105,102,105,99,97,116,101,60,47,107,101,121,62,10,9,60,100,97,116,97,62,10,9,76,83,48,116,76,83,49,67,82,85,100,74,84,105,66,68,82,86,74,85,83,85,90,74,81,48,70,85,82,83,48,116,76,83,48,116,67,107,49,74,83,85,78,49,97,107,78,68,81,87,70,76,90,48,70,51,83,85,74,66,90,48,108,67,81,85,82,66,10,9,84,107,74,110,97,51,70,111,97,50,108,72,79,88,99,119,81,107,70,82,86,85,90,66,82,69,70,66,84,85,73,48,87,69,82,85,82,84,86,78,82,71,116,51,84,87,112,70,77,48,49,69,87,84,65,75,84,109,120,118,87,69,82,85,83,84,86,78,10,9,82,71,100,54,84,85,82,70,77,48,49,69,87,84,66,79,98,71,57,51,81,85,82,68,81,48,70,84,83,88,100,69,85,86,108,75,83,50,57,97,83,87,104,50,89,48,53,66,85,85,86,67,81,108,70,66,82,71,100,110,82,86,66,66,82,69,78,68,10,9,81,86,70,118,81,119,112,110,90,48,86,67,81,85,116,119,78,86,112,105,83,68,100,120,97,106,100,121,78,48,57,78,101,72,100,79,83,110,108,70,85,106,66,114,85,48,108,117,81,50,49,53,78,109,57,90,79,85,57,90,81,106,90,53,83,72,82,119,10,9,79,69,116,84,78,67,56,49,100,68,86,81,101,107,57,87,100,107,53,117,87,109,48,48,67,110,100,84,97,70,66,85,101,107,111,121,99,48,115,50,75,50,57,122,99,107,85,49,79,72,70,54,97,108,104,50,78,85,78,107,77,84,78,72,77,110,86,75,10,9,82,84,104,52,78,122,69,122,98,106,108,113,98,110,74,75,90,50,107,49,97,108,107,120,81,88,69,122,83,106,100,113,82,108,100,97,82,49,111,119,87,109,73,75,90,109,107,114,97,51,66,72,77,110,86,107,83,68,78,85,89,50,112,115,99,85,74,74,10,9,99,110,89,122,84,108,104,118,86,84,89,119,79,71,57,69,83,106,104,77,97,108,66,111,82,71,74,113,89,51,104,72,85,107,49,119,84,69,120,79,78,68,108,70,85,110,86,74,77,108,65,50,82,108,86,77,99,70,112,87,84,119,112,104,82,107,70,112,10,9,83,84,108,73,84,70,74,73,97,69,74,51,86,85,120,52,99,85,57,118,78,107,107,119,81,87,120,85,83,106,90,77,90,108,78,82,100,88,108,88,97,72,74,118,87,87,120,116,97,109,120,77,101,72,86,78,90,122,78,54,85,86,78,49,98,107,116,121,10,9,81,109,74,89,81,84,70,97,78,67,57,81,67,107,112,105,97,51,70,83,99,109,70,66,81,106,99,118,83,49,99,50,81,122,74,104,87,70,86,76,98,108,112,108,97,84,90,112,87,108,78,112,85,85,57,69,87,107,53,117,86,51,107,119,79,72,78,119,10,9,86,68,74,115,90,70,66,68,79,85,70,113,100,87,78,69,78,108,82,75,82,109,48,51,101,72,74,54,86,68,73,75,86,48,56,120,81,84,70,69,98,51,104,89,89,106,107,48,85,49,70,51,90,84,74,72,87,86,70,88,85,86,108,51,100,68,85,119,10,9,81,48,70,51,82,85,70,66,89,85,48,118,84,85,81,119,100,48,82,66,87,85,82,87,85,106,66,85,81,86,70,73,76,48,74,66,83,88,100,66,82,69,70,107,81,109,100,79,86,103,112,73,85,84,82,70,82,109,100,82,86,85,53,84,89,48,116,122,10,9,85,108,82,118,82,88,66,69,89,85,70,108,78,85,90,48,98,121,116,73,83,87,90,53,86,72,90,48,82,88,100,69,90,49,108,69,86,108,73,119,85,69,70,82,83,67,57,67,81,86,70,69,81,87,100,88,90,48,49,66,77,69,100,68,85,51,70,72,10,9,67,108,78,74,89,106,78,69,85,85,86,67,81,108,70,86,81,85,69,48,83,85,74,66,85,85,70,79,77,68,108,117,90,71,86,83,100,108,74,74,78,69,107,53,97,107,53,84,89,48,74,72,83,86,112,109,98,85,78,111,97,88,104,108,98,109,77,122,10,9,82,110,100,49,100,122,100,122,89,84,104,115,98,48,120,120,82,72,77,75,89,122,104,121,101,107,86,88,85,85,116,76,87,88,100,53,85,49,86,106,82,107,53,81,100,69,90,108,90,86,74,89,99,88,100,116,97,85,100,81,97,70,112,81,79,87,112,118,10,9,78,122,108,108,84,110,78,89,84,70,108,112,99,71,53,116,89,109,120,118,78,87,48,114,89,50,90,114,87,107,116,50,83,70,85,52,101,103,112,71,90,87,73,51,90,106,100,86,83,48,74,109,77,49,82,111,78,69,74,86,89,86,86,121,84,49,73,49,10,9,87,107,82,84,84,68,100,115,84,88,65,52,77,51,85,121,84,87,57,71,97,50,82,97,98,86,111,122,87,72,66,73,101,70,70,97,97,48,119,118,90,109,119,118,84,107,115,49,86,68,78,110,101,69,86,114,67,106,99,121,84,107,100,72,79,88,90,68,10,9,101,110,108,68,97,109,104,54,86,71,120,87,78,48,53,54,101,108,74,66,81,85,57,66,77,71,49,97,87,68,66,79,99,69,108,78,86,122,108,120,100,108,90,70,84,109,86,84,100,70,66,75,99,71,112,80,100,72,70,87,86,110,100,79,79,71,86,111,10,9,99,71,86,68,83,84,77,75,90,71,100,105,86,50,108,79,84,69,90,53,77,85,120,104,77,88,90,83,84,71,104,67,83,51,78,48,87,84,74,88,97,50,107,52,99,86,78,82,98,48,100,90,98,109,57,51,86,110,100,76,99,69,78,72,77,72,66,69,10,9,99,107,70,88,83,71,86,110,77,72,107,119,99,70,111,118,90,49,78,49,84,49,85,49,83,81,112,73,86,72,90,115,98,108,78,78,100,50,116,104,101,71,82,122,78,50,70,76,81,85,86,86,76,49,103,120,90,86,112,79,98,85,112,120,87,71,74,74,10,9,78,50,70,89,86,48,100,79,87,107,49,49,67,105,48,116,76,83,48,116,82,85,53,69,73,69,78,70,85,108,82,74,82,107,108,68,81,86,82,70,76,83,48,116,76,83,48,75,10,9,60,47,100,97,116,97,62,10,9,60,107,101,121,62,72,111,115,116,73,68,60,47,107,101,121,62,10,9,60,115,116,114,105,110,103,62,65,68,70,53,56,53,57,50,45,53,67,51,51,45,52,55,52,70,45,56,66,51,56,45,69,67,57,53,66,68,70,57,69,49,55,66,60,47,115,116,114,105,110,103,62,10,9,60,107,101,121,62,72,111,115,116,80,114,105,118,97,116,101,75,101,121,60,47,107,101,121,62,10,9,60,100,97,116,97,62,10,9,76,83,48,116,76,83,49,67,82,85,100,74,84,105,66,81,85,107,108,87,81,86,82,70,73,69,116,70,87,83,48,116,76,83,48,116,67,107,49,74,83,85,86,50,90,48,108,67,81,85,82,66,84,107,74,110,97,51,70,111,97,50,108,72,79,88,99,119,10,9,81,107,70,82,82,85,90,66,81,86,78,68,81,107,116,110,100,50,100,110,85,50,116,66,90,48,86,66,81,87,57,74,81,107,70,82,81,51,70,108,86,49,100,52,75,122,90,118,75,122,89,114,101,109,111,75,84,87,78,69,85,50,78,111,82,87,82,75,10,9,82,87,108,75,100,51,66,122,100,88,70,72,85,70,82,116,81,87,86,122,97,68,100,104,90,107,78,114,100,86,65,114,89,109,86,85,79,72,112,115,89,110,112,97,77,108,112,49,84,85,86,118,86,68,65,52,101,87,82,121,81,51,86,50,99,85,120,76,10,9,101,69,57,109,83,119,112,122,78,68,69,51,75,49,70,117,90,71,82,52,100,72,74,112,85,108,66,78,90,84,108,107,78,83,57,90,78,84,90,53,87,85,108,49,87,84,74,79,85,85,116,48,101,87,85,48,101,70,90,116,85,109,49,107,82,49,99,122,10,9,78,72,90,119,83,49,74,48,99,109,53,83,79,84,65,122,83,84,86,104,90,49,78,76,67,106,99,53,101,108,89,50,82,107,57,48,85,69,116,66,101,87,90,68,78,72,111,48,85,84,73,48,77,48,49,83,97,49,82,76,85,51,108,54,90,86,66,83,10,9,82,87,74,112,84,109,111,114,97,70,90,68,78,108,100,87,86,71,49,111,85,85,108,112,85,70,74,53,77,70,73,48,85,87,78,71,81,122,104,104,97,110,69,75,84,50,108,79,81,85,112,86,101,87,86,112,77,122,66,114,84,72,78,115,98,50,69,50,10,9,82,48,112,97,98,122,86,84,79,71,74,113,83,85,52,52,77,69,86,121,99,72,108,120,100,49,99,120,100,48,53,88,90,86,66,54,101,86,99,49,83,50,116,104,77,109,100,66,90,83,57,53,98,72,86,110,100,71,49,115,77,81,112,68,99,68,74,89,10,9,98,51,86,118,98,86,86,118,97,48,82,110,77,108,82,97,77,88,78,48,85,69,120,76,86,84,108,119,87,70,82,51,100,108,70,74,78,50,53,66,75,50,116,53,85,108,112,49,79,71,69,52,77,68,108,115,97,110,82,82,84,108,69,50,84,86,89,121,10,9,76,50,86,70,97,48,49,73,100,71,104,116,67,107,86,71,97,48,100,78,84,71,86,107,81,87,100,78,81,107,70,66,82,85,78,110,90,48,86,66,85,108,112,121,101,72,86,109,77,87,85,48,100,109,100,113,99,109,104,83,87,71,90,107,87,70,82,83,10,9,85,87,53,88,97,48,100,70,97,49,78,104,86,122,86,48,84,48,78,113,89,86,103,114,77,70,70,113,87,69,115,75,78,109,57,48,77,72,86,73,86,87,78,72,77,106,100,88,81,109,74,114,87,107,120,84,84,107,48,121,76,50,73,48,87,110,112,70,10,9,101,71,86,82,90,72,107,114,85,48,104,107,81,48,74,53,82,85,57,104,90,110,112,84,101,107,108,104,83,87,49,114,81,50,74,53,77,50,53,104,97,68,66,54,81,49,86,50,84,103,112,107,97,85,48,50,82,106,90,117,101,88,103,114,84,69,74,78,10,9,97,50,57,85,84,48,53,77,83,110,112,73,99,110,65,120,78,107,112,119,85,109,108,90,85,50,49,122,85,87,74,106,82,67,115,118,85,88,78,72,78,86,77,119,85,69,99,118,89,87,53,77,98,68,82,120,86,88,70,105,100,71,82,116,81,105,116,122,10,9,67,108,74,80,85,71,120,50,87,106,70,66,78,87,49,74,78,88,69,119,75,51,70,50,77,107,112,107,98,69,49,86,85,70,85,52,98,87,70,83,97,88,104,78,78,109,57,86,84,122,100,119,90,50,120,120,82,106,90,71,77,85,53,49,99,109,77,122,10,9,98,72,89,114,78,85,104,88,77,87,70,73,90,122,100,90,89,105,115,75,84,87,112,90,84,122,86,75,84,69,90,106,97,51,85,114,82,108,100,110,89,49,66,121,79,72,69,52,82,109,100,106,82,68,104,80,86,70,108,109,84,122,74,54,89,48,53,112,10,9,101,70,73,121,82,84,82,87,85,122,77,119,101,107,70,82,83,86,112,117,87,107,53,106,82,48,116,121,89,48,49,90,78,71,82,106,81,103,111,50,85,48,108,109,97,109,86,109,98,109,107,51,82,71,99,119,100,50,104,78,100,122,78,53,90,50,107,122,10,9,77,70,112,106,81,109,100,97,78,85,49,105,87,106,74,122,81,87,53,74,75,49,82,107,87,108,70,76,81,109,100,82,82,70,112,105,83,106,82,114,90,107,52,50,85,109,99,50,99,84,103,52,84,87,116,118,67,108,70,72,77,107,120,82,83,110,70,83,10,9,87,85,70,111,85,109,116,111,77,84,108,76,78,122,86,117,87,110,90,115,84,85,120,121,97,51,112,76,98,51,82,66,98,87,49,74,97,70,100,73,97,69,108,51,83,87,120,114,98,87,78,80,90,122,78,67,86,50,57,120,77,83,116,54,101,88,90,110,10,9,77,85,104,89,100,69,77,75,97,122,66,117,101,72,78,105,84,110,99,48,78,109,112,115,84,49,108,86,77,69,69,53,84,70,90,106,90,109,82,113,84,108,100,78,83,85,103,121,83,85,112,54,101,70,90,82,86,87,107,49,90,50,70,118,84,70,74,81,10,9,79,87,120,108,98,48,112,48,84,50,108,107,98,68,100,72,85,85,73,122,89,87,90,53,81,103,112,82,76,49,90,88,98,122,66,108,101,71,78,111,84,69,70,75,79,83,116,116,90,69,78,85,77,69,53,115,86,51,74,122,100,48,116,67,90,49,70,69,10,9,83,88,86,71,81,87,52,48,84,88,70,106,83,87,108,82,85,50,111,119,81,85,108,112,84,48,53,84,83,106,70,90,85,107,104,118,101,68,85,49,99,71,74,83,67,108,86,107,90,86,104,78,85,68,89,50,98,70,108,111,83,69,89,48,86,109,74,111,10,9,90,105,57,116,98,88,73,122,78,87,74,77,86,85,49,51,82,108,78,78,81,122,90,67,98,69,116,73,98,85,86,113,100,87,103,53,81,87,49,106,98,50,104,54,78,84,74,121,90,105,116,105,81,109,77,50,77,50,49,52,98,109,119,75,97,86,65,118,10,9,86,86,107,120,82,72,108,121,77,72,70,110,87,85,100,118,98,71,53,85,78,84,66,85,90,50,74,122,84,110,70,83,79,69,74,74,99,48,82,114,89,50,85,48,84,106,90,73,87,72,108,73,97,48,120,74,99,108,65,122,101,87,90,97,83,69,48,121,10,9,83,71,49,114,98,48,49,105,83,110,74,69,77,81,112,87,86,86,89,52,89,49,74,70,98,109,74,51,83,48,74,110,83,69,116,97,87,107,112,87,87,84,69,51,99,50,82,68,97,84,86,68,85,68,108,84,90,87,86,79,78,110,89,52,78,71,104,53,10,9,90,69,112,66,81,48,86,48,89,106,85,50,98,50,73,122,78,107,116,112,77,84,89,53,98,107,82,77,79,87,108,112,67,108,74,48,101,107,116,114,79,70,66,78,78,122,107,122,79,87,108,109,87,107,49,104,98,48,108,89,99,87,89,51,84,69,100,97,10,9,78,88,82,97,99,68,74,71,98,51,74,69,98,122,107,114,99,87,120,119,82,84,66,71,101,106,74,105,82,48,116,84,90,71,120,52,87,68,82,108,82,87,56,114,97,87,78,50,99,122,73,75,97,50,116,97,90,88,86,120,82,85,112,74,100,85,78,71,10,9,78,87,81,121,85,109,107,50,99,85,57,54,76,50,49,119,81,48,57,54,98,48,78,85,87,109,82,68,98,48,74,104,77,108,112,50,77,110,99,120,98,70,77,50,100,109,100,68,84,50,78,82,89,88,69,122,89,51,90,66,98,48,100,67,81,85,120,66,10,9,100,103,112,84,85,72,108,90,82,71,57,68,89,86,104,54,100,85,82,85,98,72,86,50,90,107,108,118,81,49,78,86,85,71,104,118,99,48,82,115,99,108,70,68,101,109,74,68,81,87,116,80,78,86,70,109,78,108,99,119,100,72,78,113,99,51,108,71,10,9,90,110,86,109,87,69,111,122,101,68,65,52,83,85,120,116,83,51,78,79,67,107,86,90,79,84,86,52,89,85,78,105,99,85,100,122,81,50,112,50,87,83,116,78,83,107,70,82,82,68,66,48,84,105,56,51,84,50,86,112,77,68,89,120,100,48,108,117,10,9,77,49,99,122,97,85,116,106,86,48,82,52,81,85,104,48,90,106,74,83,81,108,73,49,86,70,99,121,97,86,69,51,99,107,90,109,84,71,85,75,83,108,108,106,83,85,104,112,83,69,70,122,83,122,104,105,98,86,70,114,99,68,69,114,98,85,120,120,10,9,99,86,100,50,90,86,82,71,79,84,108,48,99,85,78,77,84,50,57,106,90,108,86,110,77,85,70,118,82,48,74,66,83,85,116,110,98,69,49,68,83,51,66,118,101,72,85,50,99,71,49,51,85,71,57,104,77,65,111,122,98,71,69,50,101,107,86,68,10,9,86,85,82,110,77,85,53,121,90,87,73,50,90,68,85,114,98,70,86,116,77,106,82,77,87,85,78,69,97,122,78,50,89,88,108,104,99,49,70,122,79,87,103,121,86,86,104,54,84,85,70,115,86,110,108,76,99,85,86,70,75,49,104,69,101,88,73,53,10,9,82,68,108,97,99,49,89,119,67,107,100,104,98,107,90,106,86,108,70,120,100,106,66,118,100,106,100,106,90,88,66,66,82,107,81,51,82,110,74,115,90,106,65,51,79,69,120,82,77,48,90,90,89,84,74,110,89,85,49,66,84,49,112,71,89,106,70,81,10,9,100,48,56,50,77,109,74,117,90,72,108,83,86,85,49,121,99,72,108,114,84,83,116,52,81,88,73,75,97,51,74,84,87,86,66,110,78,51,89,114,98,85,49,87,81,86,90,54,82,85,112,86,98,109,111,119,77,105,57,117,67,105,48,116,76,83,48,116,10,9,82,85,53,69,73,70,66,83,83,86,90,66,86,69,85,103,83,48,86,90,76,83,48,116,76,83,48,75,10,9,60,47,100,97,116,97,62,10,9,60,107,101,121,62,82,111,111,116,67,101,114,116,105,102,105,99,97,116,101,60,47,107,101,121,62,10,9,60,100,97,116,97,62,10,9,76,83,48,116,76,83,49,67,82,85,100,74,84,105,66,68,82,86,74,85,83,85,90,74,81,48,70,85,82,83,48,116,76,83,48,116,67,107,49,74,83,85,78,121,86,69,78,68,81,86,112,88,90,48,70,51,83,85,74,66,90,48,108,67,81,85,82,66,10,9,84,107,74,110,97,51,70,111,97,50,108,72,79,88,99,119,81,107,70,82,86,85,90,66,82,69,70,66,84,85,73,48,87,69,82,85,82,84,86,78,82,71,116,51,84,87,112,70,77,48,49,69,87,84,65,75,84,109,120,118,87,69,82,85,83,84,86,78,10,9,82,71,100,54,84,85,82,70,77,48,49,69,87,84,66,79,98,71,57,51,81,85,82,68,81,48,70,84,83,88,100,69,85,86,108,75,83,50,57,97,83,87,104,50,89,48,53,66,85,85,86,67,81,108,70,66,82,71,100,110,82,86,66,66,82,69,78,68,10,9,81,86,70,118,81,119,112,110,90,48,86,67,81,85,120,108,97,85,78,49,86,108,104,49,86,110,90,120,97,67,116,66,99,85,70,104,85,122,70,112,89,108,78,121,100,70,112,118,98,68,104,121,79,87,49,82,100,107,74,74,90,108,82,105,97,107,86,113,10,9,84,48,49,54,89,107,119,51,98,106,100,79,86,110,100,67,89,85,70,88,90,109,90,82,67,108,112,78,89,87,74,85,85,84,86,109,83,87,120,78,100,105,57,74,83,86,81,53,81,50,119,53,85,106,66,82,87,69,104,51,86,83,115,50,98,72,74,84,10,9,79,70,100,69,99,72,69,48,84,87,57,52,87,109,82,108,86,50,57,86,97,68,86,68,87,87,74,53,83,72,108,89,81,49,104,67,78,107,90,122,84,85,119,75,78,109,86,48,76,50,81,53,100,87,90,118,81,51,112,71,87,69,112,74,79,87,90,66,10,9,101,108,70,118,89,87,120,78,84,106,78,74,81,85,116,54,98,84,104,82,84,72,112,52,97,85,78,119,86,109,108,75,100,86,90,113,81,87,70,121,86,122,90,49,90,49,112,119,82,48,107,48,84,72,82,105,84,51,107,51,83,81,111,114,99,49,78,90,10,9,84,108,82,116,98,85,116,72,97,107,82,86,97,87,104,122,81,49,108,120,89,84,104,114,85,110,66,50,97,107,86,105,85,87,56,53,77,71,82,78,82,86,86,72,81,49,90,51,84,107,70,72,89,51,82,86,81,107,86,85,84,107,120,107,97,109,120,120,10,9,98,107,100,73,87,108,100,67,83,106,74,73,67,107,99,48,101,70,100,68,85,48,77,119,89,110,104,104,90,69,90,77,86,69,78,49,98,48,111,52,78,84,86,75,83,106,86,78,86,50,69,114,82,70,108,75,82,108,66,110,87,86,90,120,82,107,57,120,10,9,85,68,70,73,90,109,104,105,84,72,74,108,81,109,49,121,89,50,53,81,90,70,108,104,78,69,70,73,79,68,81,75,100,87,107,120,82,122,81,51,82,106,70,113,90,51,90,119,84,69,74,86,89,50,57,50,81,108,77,50,75,122,81,49,85,105,57,70,10,9,81,48,70,51,82,85,70,66,89,85,49,53,84,85,82,66,100,48,82,51,87,85,82,87,85,106,66,85,81,86,70,73,76,48,74,66,86,88,100,66,100,48,86,67,76,51,112,66,90,65,112,67,90,48,53,87,83,70,69,48,82,85,90,110,85,86,86,72,10,9,99,50,78,54,100,70,70,119,98,86,78,52,84,70,82,76,87,109,108,68,85,69,108,71,84,67,57,51,79,87,90,78,85,85,49,51,82,70,70,90,83,107,116,118,87,107,108,111,100,109,78,79,81,86,70,70,82,107,74,82,81,85,82,110,90,48,86,67,10,9,67,107,70,69,82,109,69,51,78,85,120,66,82,48,53,113,83,85,70,88,98,122,104,70,86,86,100,83,83,109,57,97,76,49,90,86,98,106,82,67,99,51,86,108,101,72,112,67,90,107,53,81,87,106,66,121,86,122,66,120,81,50,53,71,100,68,73,120,10,9,89,121,115,48,83,69,48,48,86,70,103,114,78,106,108,116,89,108,103,75,84,107,70,53,82,106,78,51,101,86,78,88,77,49,78,88,83,71,108,85,83,48,104,81,81,85,78,52,82,50,81,53,82,69,89,120,86,50,70,82,84,51,104,111,100,106,82,76,10,9,89,87,70,75,99,71,89,52,87,86,74,53,97,69,86,83,75,48,116,111,81,51,74,90,83,86,86,104,76,49,108,87,89,86,86,108,81,103,111,49,98,109,57,49,86,70,89,53,90,48,120,118,98,86,74,74,79,87,57,110,75,48,116,76,89,107,53,122,10,9,78,69,120,104,87,85,70,84,89,50,57,113,78,106,66,78,100,109,100,74,90,68,66,53,87,68,82,86,98,108,104,77,90,108,78,71,100,87,57,77,99,87,90,72,99,69,74,90,77,50,108,52,99,48,57,112,67,107,74,105,101,85,82,104,81,87,120,84,10,9,99,68,74,105,76,122,70,88,77,88,78,51,100,121,116,72,87,84,74,72,82,110,65,49,90,110,112,50,98,110,74,52,78,68,90,48,85,109,86,70,90,72,78,121,84,109,111,51,100,70,70,121,99,85,70,76,85,107,70,109,99,106,89,51,84,122,104,119,10,9,99,48,77,119,77,110,65,75,90,48,53,117,78,85,90,54,99,85,86,72,83,51,74,122,99,71,107,121,82,69,104,88,86,88,81,114,89,108,86,78,83,85,49,120,85,85,48,52,85,122,90,48,75,49,66,78,101,108,104,119,90,110,74,81,90,109,86,78,10,9,77,110,90,79,86,71,57,119,90,50,116,109,82,110,81,120,86,48,112,73,99,48,78,66,87,81,111,49,85,109,90,51,86,109,85,120,97,51,85,52,90,121,116,82,90,67,57,71,83,50,90,97,84,86,90,80,84,84,48,75,76,83,48,116,76,83,49,70,10,9,84,107,81,103,81,48,86,83,86,69,108,71,83,85,78,66,86,69,85,116,76,83,48,116,76,81,111,61,10,9,60,47,100,97,116,97,62,10,9,60,107,101,121,62,82,111,111,116,80,114,105,118,97,116,101,75,101,121,60,47,107,101,121,62,10,9,60,100,97,116,97,62,10,9,76,83,48,116,76,83,49,67,82,85,100,74,84,105,66,81,85,107,108,87,81,86,82,70,73,69,116,70,87,83,48,116,76,83,48,116,67,107,49,74,83,85,86,50,90,48,108,67,81,85,82,66,84,107,74,110,97,51,70,111,97,50,108,72,79,88,99,119,10,9,81,107,70,82,82,85,90,66,81,86,78,68,81,107,116,110,100,50,100,110,85,50,116,66,90,48,86,66,81,87,57,74,81,107,70,82,81,122,78,118,90,51,74,115,86,106,100,115,89,106,90,118,90,109,99,75,83,50,100,72,97,51,82,90,98,84,66,120,10,9,78,49,100,104,83,109,90,76,76,49,112,114,84,72,100,84,83,68,65,121,78,72,104,74,101,109,112,78,77,110,107,114,78,83,116,54,86,109,78,66,86,50,100,71,98,106,77,119,82,49,82,72,98,84,65,119,84,49,104,53,83,108,82,77,76,51,108,68,10,9,82,83,57,82,99,65,112,109,86,87,82,70,82,110,103,52,82,108,66,49,99,71,69,119,100,107,90,110,78,109,70,49,82,69,116,78,86,49,104,89,98,72,70,71,83,87,86,82,98,85,99,52,97,68,104,115,100,50,120,51,90,87,104,105,82,69,77,114,10,9,98,110,74,109,77,50,90,105,98,106,90,66,99,51,104,87,101,86,78,81,87,72,100,78,67,106,66,76,82,51,66,85,82,71,82,53,81,85,78,122,78,88,90,70,81,122,103,52,87,87,100,120,86,108,108,112,89,109,120,90,100,48,100,120,77,88,86,121,10,9,98,48,100,104,85,109,108,80,81,122,100,88,101,110,78,49,101,86,66,121,82,87,49,69,86,84,86,119,97,87,104,118,100,122,70,74,98,50,74,66,98,85,115,75,98,88,90,75,82,87,70,105,78,72,104,72,77,69,116,81,90,69,104,85,81,107,90,67,10,9,90,50,120,106,82,70,70,67,98,107,120,87,81,86,74,70,101,108,77,122,87,84,86,104,99,72,104,111,77,108,90,110,85,50,82,111,101,72,86,78,86,109,100,114,90,51,82,72,79,70,100,117,85,108,77,119,100,51,74,120,81,119,112,109,84,50,86,84,10,9,85,50,86,85,82,109,49,50,90,122,74,68,85,108,81,48,82,48,90,104,97,70,82,120,97,106,108,83,77,122,82,88,101,84,89,122,90,49,112,120,77,48,112,54,77,49,100,72,100,85,70,67,76,48,57,77,98,51,82,83,100,85,57,52,90,70,107,48,10,9,84,68,90,84,100,49,90,73,83,48,120,51,67,108,86,49,100,110,86,80,86,87,90,52,81,87,100,78,81,107,70,66,82,85,78,110,90,48,86,67,81,85,116,78,86,48,78,122,79,68,104,97,89,87,69,48,86,48,70,52,81,110,100,114,100,109,103,122,10,9,98,109,74,84,100,85,57,118,78,107,108,104,97,108,78,54,86,87,104,83,86,48,49,79,85,49,81,121,100,110,99,75,79,86,69,50,99,49,108,115,77,69,104,73,101,68,78,106,101,85,70,119,83,51,112,109,86,48,90,73,78,84,86,81,78,84,70,66,10,9,101,85,108,109,85,68,66,109,84,71,100,78,85,110,108,120,77,88,112,111,99,105,116,114,86,51,100,51,85,84,90,107,99,86,103,50,85,49,70,119,86,88,86,87,101,69,112,105,85,81,112,85,99,88,81,49,99,86,86,113,90,71,70,122,97,84,69,49,10,9,86,109,115,52,86,68,78,108,86,69,49,90,84,50,89,53,84,86,90,80,86,88,74,84,90,86,104,117,98,86,82,74,84,85,70,88,99,107,104,107,86,51,66,51,77,70,82,117,76,51,78,49,82,106,70,52,97,72,78,117,77,87,74,67,78,68,66,54,10,9,67,108,78,80,89,109,81,121,99,110,82,90,98,51,99,52,82,50,49,86,75,50,104,51,78,122,104,121,98,122,78,105,89,84,66,110,89,122,78,85,90,69,89,53,89,86,103,51,83,109,86,112,78,87,82,106,99,50,112,108,83,87,116,73,87,88,74,50,10,9,77,69,53,48,76,51,66,76,97,71,89,114,83,69,82,68,99,108,89,75,84,83,116,114,84,107,90,78,78,68,86,109,82,121,116,53,82,86,108,116,83,107,116,69,83,109,116,48,98,48,86,106,82,48,112,51,83,110,69,53,100,85,86,104,89,50,70,86,10,9,89,88,66,54,82,108,112,84,100,86,112,112,100,108,69,118,100,50,108,71,82,87,104,78,82,70,86,71,75,49,100,76,79,70,69,118,97,119,111,120,98,106,78,107,97,86,74,79,86,70,111,118,89,86,78,75,87,88,112,104,85,122,70,119,99,86,90,88,10,9,78,50,111,49,83,72,103,52,85,107,53,88,81,107,104,118,79,87,116,107,86,70,108,67,97,85,86,70,81,50,100,90,82,85,69,49,89,109,108,69,87,70,78,84,89,108,70,69,86,48,81,51,77,69,49,70,67,110,104,120,82,49,70,110,83,87,103,53,10,9,90,71,100,120,81,108,112,87,78,48,57,71,100,68,66,86,100,70,107,114,97,87,112,70,97,107,78,110,99,48,112,116,82,68,104,121,90,87,112,70,99,122,74,50,86,84,86,117,84,109,70,85,82,71,119,118,87,88,78,81,100,122,85,52,83,109,120,77,10,9,90,87,49,87,77,68,85,75,76,50,100,87,82,110,66,85,90,87,104,117,85,110,100,108,78,70,108,79,87,68,100,66,82,108,90,74,89,85,90,67,100,86,100,87,86,87,108,73,83,69,112,120,89,86,100,115,79,71,78,48,84,86,90,118,79,68,100,105,10,9,81,87,48,52,81,87,104,66,78,72,90,84,81,86,70,113,87,72,108,86,83,72,108,53,97,119,112,71,82,110,74,76,90,49,107,49,101,109,78,117,85,109,82,67,89,83,116,74,79,85,69,51,97,85,99,114,97,107,112,81,98,84,66,68,90,49,108,70,10,9,81,88,112,76,85,70,82,105,75,48,108,51,100,68,85,118,85,110,70,114,101,86,100,73,83,50,53,78,83,107,74,85,100,48,112,108,86,68,74,120,81,85,49,77,67,109,90,81,78,49,81,120,97,106,86,89,90,86,66,85,99,105,57,106,97,69,78,67,10,9,100,88,73,118,101,72,82,78,78,109,49,53,81,110,99,51,97,69,90,70,83,105,116,116,84,87,108,67,90,68,100,50,87,71,57,69,99,122,108,79,82,71,104,81,87,71,119,120,81,85,104,69,86,48,70,69,99,48,82,90,78,85,89,75,76,51,86,54,10,9,78,87,49,116,97,49,100,120,82,48,56,118,83,109,57,114,85,110,112,119,85,88,107,51,85,84,82,80,100,108,90,121,84,48,108,89,84,107,90,71,77,110,82,113,83,50,104,117,77,69,108,83,87,85,74,118,81,48,74,83,84,51,74,90,84,85,53,90,10,9,101,107,116,107,98,48,49,51,86,72,70,83,77,103,111,122,87,69,116,114,90,72,73,122,77,107,120,83,86,85,78,110,87,85,73,122,90,84,74,81,90,48,69,120,86,84,82,121,86,106,66,71,81,50,111,114,98,88,74,74,100,48,82,81,98,110,69,50,10,9,79,87,74,89,90,72,70,48,86,70,108,106,87,68,99,114,76,48,86,115,87,86,99,53,85,69,104,50,85,48,120,116,67,109,53,108,89,109,56,48,78,71,57,68,83,110,66,67,99,85,73,120,100,88,100,90,77,88,78,104,83,108,70,108,85,72,107,120,10,9,85,106,90,82,98,69,108,84,90,107,89,121,81,85,90,75,83,109,74,121,81,121,116,117,99,109,90,66,81,48,86,104,84,109,78,54,87,87,53,118,101,88,90,120,85,72,108,87,90,70,73,75,97,69,112,89,100,86,86,74,87,108,74,70,77,71,108,107,10,9,78,87,86,97,81,122,66,73,99,50,108,104,77,86,108,82,99,49,82,90,79,87,112,77,84,105,115,122,99,49,108,121,87,88,66,79,84,71,86,97,97,86,86,111,77,51,82,107,84,70,108,53,85,70,112,104,82,50,86,107,85,85,116,67,90,48,90,120,10,9,81,81,112,49,89,87,53,119,99,72,104,74,84,51,66,73,84,109,116,116,78,84,100,111,98,86,89,51,78,51,99,49,98,67,116,51,87,71,82,106,98,49,100,66,84,50,78,54,82,106,70,78,84,88,66,87,101,68,74,113,90,71,100,67,87,67,57,76,10,9,82,83,116,80,89,84,82,85,90,110,90,67,83,85,53,118,84,84,100,116,67,107,70,54,97,107,48,50,90,108,82,76,86,49,108,113,86,48,82,112,78,87,53,106,90,70,90,119,86,87,112,79,81,109,82,84,85,88,66,117,79,88,77,121,90,51,77,119,10,9,76,49,104,77,77,51,78,73,77,70,100,54,99,86,78,83,99,109,82,117,99,70,70,115,86,86,69,49,85,69,116,68,90,87,116,111,90,109,103,75,89,109,49,73,87,86,78,75,90,84,86,88,79,68,90,48,90,107,81,52,101,84,108,66,84,109,69,121,10,9,84,83,57,67,81,108,86,83,81,50,108,68,79,68,77,122,83,70,78,73,87,72,74,67,97,69,70,118,82,48,74,66,84,72,66,109,90,70,104,104,82,84,70,115,86,109,77,52,84,68,108,85,82,122,82,51,78,81,112,86,100,69,74,84,85,109,90,114,10,9,99,71,104,115,77,71,57,112,85,107,70,53,86,106,65,50,86,110,100,66,89,49,77,51,97,85,111,49,83,110,108,68,100,85,82,115,89,85,112,119,81,107,116,86,86,71,104,121,84,71,70,74,90,106,74,115,85,109,74,50,84,69,112,104,99,50,108,115,10,9,87,87,48,53,89,50,74,76,67,107,77,49,78,122,82,89,83,48,78,89,79,87,57,105,82,107,90,115,87,107,78,114,81,84,86,72,85,51,70,118,84,70,108,122,84,86,104,77,76,50,74,112,99,106,100,70,79,87,78,71,76,122,107,48,79,69,78,89,10,9,100,68,100,67,98,86,78,106,81,108,100,82,100,87,70,66,82,84,86,113,99,107,77,48,98,83,56,75,90,85,100,54,78,50,86,106,86,70,66,109,82,107,89,120,78,70,82,109,81,108,85,51,79,85,120,105,86,50,104,82,67,105,48,116,76,83,48,116,10,9,82,85,53,69,73,70,66,83,83,86,90,66,86,69,85,103,83,48,86,90,76,83,48,116,76,83,48,75,10,9,60,47,100,97,116,97,62,10,9,60,107,101,121,62,83,121,115,116,101,109,66,85,73,68,60,47,107,101,121,62,10,9,60,115,116,114,105,110,103,62,66,49,54,67,65,67,50,53,45,56,65,57,54,45,52,49,69,50,45,57,70,53,48,45,50,52,50,54,70,51,51,49,50,56,49,65,60,47,115,116,114,105,110,103,62,10,9,60,107,101,121,62,87,105,70,105,77,65,67,65,100,100,114,101,115,115,60,47,107,101,121,62,10,9,60,115,116,114,105,110,103,62,57,48,58,98,48,58,101,100,58,99,99,58,52,57,58,55,101,60,47,115,116,114,105,110,103,62,10,60,47,100,105,99,116,62,10,60,47,112,108,105,115,116,62,10]}}`

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 5.2.7
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.803.3
   @angular-devkit/schematics    : 8.3.3
   @angular/cli                  : 8.3.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 15 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v11.6.0 (/usr/local/bin/node)
   npm        : 6.11.3
   OS         : macOS Mojave
   Xcode      : Xcode 11.0 Build version 11A420a
```

**Other Information:**
I recently updated my iOS version to iOS13 and my Xcode version to 11.0. I did not make any changes to the packages or plugins.

**Comment by fatinyazi** [comment]
There are others who are also experiencing this: https://forum.ionicframework.com/t/help-needed-ionic-cordova-run-ios-device-problem-on-ios-13/174015

**Comment by bnallmaster** [comment]
I am having the exact same issue after updating to the new Xcode this week and updating my iPhone to ios 13.1.

**Comment by neontuna** [comment]
Same issue here, here my ionic info output

```
Ionic:

   Ionic CLI                     : 5.4.1 (/Users/justin/.nvm/versions/node/v11.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic 5.4.4, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 7 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.8

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v11.15.0 (/Users/justin/.nvm/versions/node/v11.15.0/bin/node)
   npm        : 6.11.2
   OS         : macOS Mojave
   Xcode      : Xcode 11.0 Build version 11A420a
```

**Comment by tebantebanteban** [comment]
same here 

```
Ionic:

   Ionic CLI                     : 5.4.1
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.803.6
   @angular-devkit/schematics    : 8.3.6
   @angular/cli                  : 8.3.6
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 26 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.11.0 (/Users/estebanrodriguez/.nvm/versions/node/v10.11.0/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 11.0 Build version 11A420a
```

**Comment by willemserik** [comment]
same problem here...

**Comment by dalemugford** [comment]
Same as well.. Can only get the app loaded on an iPhone using Xcode..

**Comment by giladrom** [comment]
So this worked for me just now:

1. Upgrade native-run to the latest version
2. ionic cordova run ios -lc --device --address=0.0.0.0

Seems to run my app (iOS13.1 with Xcode 11) just fine using live reload.

**Comment by brownoxford** [comment]
@fatinyazi Can you update your ionic-cli to v5.4.1? It looks like you are running into the issue fixed with #4156

**Comment by dalemugford** [comment]
I've updated  ionic-cli (ionic), to no avail. Hangs on `native-run ios --app platforms/ios/build/device/Findex.ipa --device --forward 8100:8100`

**Comment by willemserik** [comment]
updated native-run and still the same problem. I can only run it on simulator. via Xcode i can run it on my device also so I think it has something to do with ionic

**Comment by willemserik** [comment]
I followed #4162 and updated ionic CLI but it still doesn't work for me

**Comment by bnallmaster** [comment]
I updated to 5.4.2 and am still seeing the iOS livereload hang up issue. I also updated my native-run to the latest.

**Comment by willemserik** [comment]
After updating ionic I can't even run it on emulator anymore

**Comment by brownoxford** [comment]
Ok, I am trying to reproduce - if you have not already done so can you please post your `ionic info` output and the exact commands that are failing for you?

**Comment by willemserik** [comment]
ionic info:

`Ionic:

   Ionic CLI                     : 5.4.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 14 other plugins)

Utility:

   cordova-res : 0.3.0 (update available: 0.6.0)
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.0.2 (/Users/erikwillems/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.15.3 (/usr/local/bin/node)
   npm               : 6.11.3
   OS                : macOS Mojave
   Xcode             : Xcode 11.0 Build version 11A420a`

failing command:

`ionic cordova run ios -l --address=0.0.0.0 --verbose`

**Comment by dwieeb** [comment]
`ionic cordova run ios -l --external` works for me

**Comment by willemserik** [comment]
not for me, still the same output

**Comment by dwieeb** [comment]
@willemserik The fix is in 5.4.2, it looks like you're on 5.4.1

**Comment by willemserik** [comment]
I upgrade to 5.4.2 but still the same problem, I downgraded back to 5.4.1

**Comment by brownoxford** [comment]
@dwieeb what version of XCode are you runing? I've updated to `Xcode 11.0 Build version 11A420a` and can reproduce hang again.

**Comment by willemserik** [comment]
yes I have that version also, I don't see a newer version in the app store

**Comment by brownoxford** [comment]
@dwieeb - definitely see the hang in native run, these commands are working for me with --no-native-run. I've tried adding `stdio: 'inherit'` to the `runNativeRun` options, but no luck.

**Comment by brownoxford** [comment]
@willemserik are you by chance running with the cordova-plugin-firebasex plugin?

**Comment by willemserik** [comment]
@brownoxford I don't have that plugin in my project

**Comment by kamekazemaster** [comment]
I can confirm the problem with ionic@5.4.2 and native-run@0.2.8

**Comment by brownoxford** [comment]
@dwieeb - I tried running native-run directly on the .ipa to rule out stdio issues, and still see the hang. Currently updating to latest iOS to continue troubleshooting

**Comment by dwieeb** [comment]
@brownoxford I'm using Xcode 11.0. The `--verbose` flag will reveal more native-run output.

**Comment by willemserik** [comment]
a new problem came up for me now. when I want to emulate on the emulator with: 
`ionic cordova emulate ios --livereload --address=0.0.0.0 --verbose --target='A9B9AECA-B326-4D19-9302-ADBC79663245'`

The app opens and closes immediately again with the following error:

`2019-10-02T16:09:44.151Z native-run Caught fatal error: { Error: There was an error launching app on simulator: An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
[native-run] The request to open "be.keuringsplatform.appmyplace" failed.
[native-run] The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified ("null").
[native-run] Underlying error (domain=FBSOpenApplicationErrorDomain, code=1):
[native-run] 	The operation couldn’t be completed. (null)
[native-run] 	(null)
[native-run] 
[native-run]     at Object.runOnSimulator (/usr/local/lib/node_modules/native-run/dist/ios/utils/simulator.js:54:15)
[native-run]     at process._tickCallback (internal/process/next_tick.js:68:7) code: undefined, exitCode: 1, data: undefined }
[native-run] ERR_UNKNOWN: There was an error launching app on simulator: An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
[native-run] The request to open "be.keuringsplatform.appmyplace" failed.
[native-run] The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified ("null").
[native-run] Underlying error (domain=FBSOpenApplicationErrorDomain, code=1):
[native-run] 	The operation couldn’t be completed. (null)
[native-run] 	(null)
`

**Comment by brownoxford** [comment]
@dwieeb, Yup, I'm currently seeing the hang on this:

```protocol:lockdown socket write: {"Command":"LookupImage","ImageType":"Developer"} +3ms```

I've tried resetting Location & Privacy as well as Network Settings as described in https://github.com/ionic-team/native-run/issues/27, and have also tried native-run 0.2.4 through @latest with no luck.

Someone on [stack overflow](https://stackoverflow.com/questions/58192497/how-to-push-an-ionic-build-to-an-ios-device-without-opening-xcode) is seeing the same.

I've been trying this with a non-prod/development build signed as a development app, and am now trying other configurations.

**Comment by dwieeb** [comment]
@willemserik That looks like this issue: https://github.com/ionic-team/native-run/issues/79

This is confusing because people are saying the issue still exists in the Ionic CLI. The issue that was fixed was a stdio error between the Ionic CLI and Cordova CLI. It sounds like the command is now hanging during the `native-run` invocation for a different reason, so I'm closing this issue.

@brownoxford I created https://github.com/ionic-team/native-run/issues/80 for this issue.

**Comment by tlancina** [comment]
Hijacking this thread for a second - can someone who has this issue please attach the log of `native-run ios --app platforms/ios/build/device/{YOUR_APP_NAME}.ipa --device --verbose > log.txt` over at https://github.com/ionic-team/native-run/issues/80? You should be able to see the app path at the end of running `ionic cordova run ios`. Thanks!

**Comment by brownoxford** [comment]
Log has been attached to https://github.com/ionic-team/native-run/issues/80

**Comment by dwieeb** [comment]
For those still seeing the issue where `native-run` is hanging for iOS, you can switch to using the legacy Cordova deploy mechanism by using the [`--no-native-run` option](https://ionicframework.com/docs/cli/commands/cordova-run#option-native-run).

**Comment by dalemugford** [comment]
> For those still seeing the issue where `native-run` is hanging for iOS, you can switch to using the legacy Cordova deploy mechanism by using the [`--no-native-run` option](https://ionicframework.com/docs/cli/commands/cordova-run#option-native-run).

I still get this using `--no-native-run`:

`2019-10-09 01:12:50.316 ios-deploy[17296:1072673] [ !! ] Error 0xe800007f: Device doesn't support wireless sync. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
ios-deploy: Command failed with exit code 253
[ERROR] An error occurred while running subprocess cordova.`

**Comment by kamekazemaster** [comment]
Having the same issue as @dalemugford

**Comment by fatinyazi** [comment]
> For those still seeing the issue where `native-run` is hanging for iOS, you can switch to using the legacy Cordova deploy mechanism by using the [`--no-native-run` option](https://ionicframework.com/docs/cli/commands/cordova-run#option-native-run).

Still cannot run on iOS. It doesn't freeze anymore but showing error same as what @dalemugford posted

**Comment by patrickchoi** [comment]
Tried with and without --no-native-run

Still get this in error messaging:

```
iPhone 7 Plus, iphoneos, arm64) a.k.a. 'pc-iphone-7' connected through USB...
[cordova]  [  0%] Looking up developer disk image
[cordova]  [ 95%] Developer disk image mounted successfully
[cordova]  2019-10-09 20:21:08.066 ios-deploy[13474:12271576] [ !! ] Error 0xe800007f: Device doesn't support wireless sync. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
[cordova]  ios-deploy: Command failed with exit code 253

```

**Comment by bnallmaster** [comment]
I am getting this with --no-native-run. 

 Error 0xe800007f: Device doesn't support wireless sync. AMDeviceStartService(device, CFSTR("com.apple.debugserver"), &gdbfd, NULL)
ios-deploy: Command failed with exit code 253

I am getting this with the regular command I had been using to livereload for iOS. Havent been able to since iOS 13. 

[native-run] ERR_UNKNOWN: Unable to retrieve simulator list
[ERROR] An error occurred while running subprocess native-run.

**Comment by marpstar** [comment]
@dalemugford @patrickchoi I've been seeing that issue recently even with older versions of the CLI. Most times the app was successfully deployed to the device, but it fails to launch programmatically. You can manually launch the app.

**Comment by patrickchoi** [comment]
Doesn't seem to be true in my case, app is not found on the phone. Wouldn't this break the live reload and console capability?

**Comment by patrickchoi** [comment]
I am running the emulator and for some reason I can see my app on my test phone. It takes build comments and can see livereload in console as well. 

What I did: Tried the ionic run command (which failed), then ran emulate command to launch Simulator, and now I get both Simulator and my test device also builds at the same time. 

I'll take it for now!

**Comment by kelpie278** [comment]
> @willemserik are you by chance running with the cordova-plugin-firebasex plugin?

Hi, I'm having the same problem and I'm running that plugin, the app gets stuck in the splash screen, do you have any info about it?

**Comment by EpicNox** [comment]
> > For those still seeing the issue where `native-run` is hanging for iOS, you can switch to using the legacy Cordova deploy mechanism by using the [`--no-native-run` option](https://ionicframework.com/docs/cli/commands/cordova-run#option-native-run).
> 
> Still cannot run on iOS. It doesn't freeze anymore but showing error same as what @dalemugford posted

It's fixed (https://github.com/ionic-team/native-run/blob/master/CHANGELOG.md#029-2019-10-15) but for me, I had to update native-run
`npm install -g native-run`

**Comment by jackie-d** [comment]
I confirm

```
brew reinstall ios-deploy
npm update -g native-run
npm update ionic
```

works to get the feature back, as also reported here

[](https://forum.ionicframework.com/t/help-needed-ionic-cordova-run-ios-device-problem-on-ios-13/174015/22)

**Comment by pinguluk** [comment]
I do have this problem, is there any other fix?
